openapi: 3.0.0
info:
  title: Cookbook-OpenAPI
  version: '1.0'
  contact:
    name: Chef
    url: low_calory_cookbook.com
    email: colory_master@gmail.com
  license:
    name: GNU General Public License v3.0
  description: Retrieve low-calory recipes.
servers:
  - url: 'http://localhost:3000'
paths:
  '/recipes/{recipeId}/ingredients':
    parameters:
      - $ref: '#/components/parameters/recipeId'
    get:
      summary: GET
      tags: []
      operationId: get-recipes-recipeId-ingredients
      description: Retreive the list of ingredients for a specific recipe.
      parameters: []
      responses:
        '200':
          description: Returns an array of ingredients.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
              examples:
                Banana parfait ingredients:
                  value:
                    - positionId: 0
                      productID: BANANA
                      amount: 50
                      unit: grams
                    - positionId: 1
                      productID: GRKYOG
                      amount: 50
                      unit: grams
                    - positionId: 2
                      productID: CINNA
                      amount: 1
                      unit: pinch
        '404':
          $ref: '#/components/responses/404'
    put:
      tags: []
      summary: PUT update of recipe ingredients
      operationId: put-recipes-recipeId-ingredients
      responses:
        '200':
          description: Recipe successfully updated.
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
      description: |-
        Update the ingredients of a specific recipe. 

        **Warning**: The content of the request body overwrites all existing ingredients for the recipe. Please make sure all ingredients, including those wihtout changes, are included in the request body.
  /recipes:
    get:
      summary: GET recipes based on a search query
      tags:
        - recipes
      operationId: get-recipes
      parameters:
        - schema:
            type: array
            example:
              - '[0,200]'
          in: query
          name: calories
          description: 'Range of calories from min to max. '
        - schema:
            type: integer
            example: 60
          in: query
          name: time
          description: Max. preparation time in minutes.
        - schema:
            type: string
            example: Banana and yoghurt parfait
            maxLength: 50
          in: query
          name: name
          description: Search for word/s present in the recipe title. Separate multiple search terms with commas. Search can include grep patterns.
        - schema:
            type: string
          in: query
          name: ingredient
          description: 'Search for a recipe with a specific ingredient. Separate multiple search terms with commas. Search can include grep patterns. '
        - schema:
            type: string
            enum:
              - vegan
              - mediterranean
              - vegetarian
            example: vegan
          in: query
          name: type
          description: 'Tag defining a subset of recipes by cuisine or diet. For a full list of tags see: www.some-link-to-tags.com'
      description: |-
        Search for recipes based on {name}, {ingredient}, {calories} or preparation {time}.

        If no query parameter is set a list of all recipes (paginated) will be returned sorted by recipe id.
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeSummary'
              examples:
                Banana parfait:
                  value:
                    - recipeId: 0
                      name: Banana and yoghurt parfait
                      photo: 'http://photo/location'
                      description: Delicious creamy sweet treat with a hint of cinnamon.
                      type: vegan
                      calories: '100'
                      time: '2'
                example-2:
                  value:
                    - recipeId: 0
                      name: Banana and yoghurt parfait
                      photo: 'http://example.com'
                      description: Delicious creamy sweet treat with a hint of cinnamon.
                      type: vegan
                      calories: '100'
                      preparationTime: 2
          description: 'Returns a list of recipes that match the search query. The summary includes a name, photo, description, the total calories and preparation time. '
        '404':
          $ref: '#/components/responses/404'
    parameters: []
    post:
      summary: POST a new recipe
      operationId: post-recipes
      responses:
        '200':
          description: Recipe succesfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  recipeId:
                    $ref: '#/components/schemas/recipeId'
                  message:
                    type: string
                    example: Success! This is the ID of your new recipe.
              examples:
                Created a new recipe:
                  value:
                    recipeId: 136
                    message: Success! This is the ID of your new recipe.
        '400':
          $ref: '#/components/responses/400'
      description: |-
        This adds a new recipe summary to the API. 

        On creation the recipe is assigned a unique recipeId and blank preparation and ingredient lists are auto-generated. These can be updated at the /recipes/{recipeId}/preparation or /recipes/{recipeId}/ingredients endpoints with [PUT] methods.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RecipeSummary'
  '/recipes/{recipeId}/preparation':
    parameters:
      - $ref: '#/components/parameters/recipeId'
    get:
      summary: GET recipe methods
      tags: []
      responses:
        '200':
          description: Returns an array of recipe steps.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Step'
              examples:
                Banana and yoghurt parfait:
                  value:
                    - order: 0
                      instruction: Chop the banana into thin slices.
                    - order: 1
                      instruction: Place in a small bowl with the yoghurt.
                    - order: 2
                      instruction: Sprinkle with cinnamon.
        '404':
          $ref: '#/components/responses/404'
      operationId: get-recipes-recipeid-preparation
      description: Retrieve the methods for a specific recipe.
    put:
      tags: []
      summary: Put update to recipe methods
      operationId: put-recipes-recipeId-preparation
      responses:
        '200':
          description: Recipe successfully updated.
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
      description: |-
        Update the entire methods section of a specific recipe. Use this to add methods to a new recipe without any pre-existing methods. To update individual steps separately please see: PUT /recipes/{recipeId}/preparation/{stepId}

        **Warning**: The content of the request body overwrites all existing methods for the recipe. Please make sure all steps, including those wihtout changes, are included in the request body.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Step'
            examples:
              Banana parfait:
                value:
                  - order: 0
                    instruction: Chop the banana into thin slices.
                  - order: 1
                    instruction: Layer half in small bowl and cover with half of the yoghurt.
                  - order: 2
                    instruction: Repeat with remaining banana and yoghurt.
                  - order: 3
                    instruction: Sprinkle with cinnamon.
        description: An array of steps to perform.
  '/recipes/{recipeId}':
    parameters:
      - $ref: '#/components/parameters/recipeId'
    get:
      summary: GET recipe summary
      tags: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeSummary'
              examples:
                Banana and yoghurt parfait:
                  value:
                    recipeId: 0
                    name: Banana and yoghurt parfait
                    photo: 'http://photo/location'
                    description: Delicious creamy sweet treat with a hint of cinnamon.
                    type: vegan
                    calories: '100'
                    time: '2'
          description: Example response.
        '404':
          $ref: '#/components/responses/404'
      operationId: get-recipes-recipeid
      description: 'Retrieve the summary for a specific recipe. '
    delete:
      tags: []
      summary: DELETE recipe
      operationId: delete-recipes-recipeId
      responses:
        '200':
          description: Recipe deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Message:
                    type: string
                    example: Recipe was succesfully deleted.
              examples:
                Recipe deleted:
                  value:
                    Message: Recipe was succesfully deleted.
        '404':
          $ref: '#/components/responses/404'
      description: |-
        Entirely remove a specific recipe from the API.

        **Warning**: This operation cannot be undone.
    put:
      tags: []
      summary: PUT update to recipe summary
      operationId: put-recipes-recipeId
      responses:
        '200':
          description: Recipe successfully updated.
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '415':
          description: Unsupported media type
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: ''
                    example: 'Unsupported media type. Please ensure the path to the image is correct and that it is a .png, .jpeg or .svg file.'
              examples:
                Unsupported media type:
                  value:
                    message: 'Unsupported media type. Please ensure the path to the image is correct and that it is a .png, .jpeg or .svg file.'
      description: 'Update the recipe summary. All key and value pairs must be supplied for the update to be successful. '
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeSummary'
        description: 'Format needed to update the summry information. '
  '/recipes/{recipeId}/ingredients/{productId}':
    parameters:
      - schema:
          type: string
        name: recipeId
        in: path
        required: true
      - schema:
          type: string
        name: productId
        in: path
        required: true
    put:
      summary: ''
      operationId: put-recipes-recipeId-ingredients-productId
      responses:
        '200':
          description: OK
    delete:
      summary: ''
      operationId: delete-recipes-recipeId-ingredients-productId
      responses:
        '200':
          description: OK
  '/recipes/{recipeId}/preparation/{stepId}':
    parameters:
      - $ref: '#/components/parameters/recipeId'
      - schema:
          type: integer
          format: int64
          minimum: 1
          example: 3
        name: stepId
        in: path
        required: true
        description: Ordinal number of a step within a recipe.
    put:
      summary: PUT update to individual step
      operationId: put-recipes-recipeId-preparation-stepId
      responses:
        '200':
          description: |-
            Recipe succesfully updated.

            All steps of the recipe are returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preparation'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
      description: |-
        Updates a single step in the methods of a specific recipe. 

        The stepId indicates the step to choose based on its ordinal position. 

        **Warning** stepId may be updated following a PUT request. Take care when updating more than one step in a recipe. If many edits are needed consider PUT /recipes/{recipeId}/preparation to replace the entire methods section at once.
    delete:
      summary: ''
      operationId: delete-recipes-recipeId-preparation-stepId
      responses:
        '200':
          description: OK
components:
  schemas:
    Ingredient:
      title: Ingredient
      type: object
      x-examples:
        Milk:
          positionId: 0
          productID: MILK
          amount: 50
          unit: mL
      properties:
        order:
          $ref: '#/components/schemas/Order'
        productID:
          type: string
          description: The unique identifier of the product. This links to the Product API.
          example: MILK
        amount:
          type: number
          example: 50
          description: Amount of the product needed.
        unit:
          type: string
          description: The unit of measurement.
          enum:
            - pinch
            - cup
            - gram
            - grams
            - mL
          example: mL
    RecipeSummary:
      title: RecipeSummary
      type: object
      x-examples:
        Banana and yoghurt parfait:
          recipeId: 0
          name: Banana and yoghurt parfait
          photo: string
          description: Delicious creamy sweet treat with a hint of cinnamon.
          type: vegan
          calories: '100'
          time: '2'
      description: ''
      properties:
        name:
          description: Title of the recipe.
          example: Banana and yoghurt parfait
          type: string
        photo:
          type: string
          description: 'Path to the current location of an image of the prepared recipe. File types: .png, .jpeg or .svg'
          format: uri
        description:
          type: string
          description: Short paragraph describing the recipe.
          example: Delicious creamy sweet treat with a hint of cinnamon.
        type:
          type: string
          description: Any diet or cuisine sub-categories the recipe is assigned to.
          example: vegan
          enum:
            - vegan
            - vegetarian
        calories:
          type: string
          description: The total calories.
          example: '100'
        preparationTime:
          type: integer
          description: The estimated preparation time in minutes.
          example: 2
          minimum: 1
      required:
        - name
    Step:
      title: Step
      type: object
      x-examples:
        example-1:
          order: 1
          instruction: Spread the avocado onto the cracker.
      properties:
        order:
          $ref: '#/components/schemas/Order'
        instruction:
          type: string
          description: The instruction for the recipe.
          example: Spread the avocado onto the cracker.
    Order:
      type: integer
      title: Order
      description: 'The position within the list. Within the API, ordinal numbers are scaled to leave spaces for updating the order with PUT methods.'
      x-examples:
        Order:
          id: 0
      format: int64
      minimum: 0
      example: 1
    recipeId:
      type: integer
      title: recipeId
      format: int64
      description: Unique recipe identifier.
      example: 136
      minimum: 0
    Preparation:
      title: Preparation
      type: array
      description: Example of a recipe with three steps.
      x-examples:
        example-1:
          - step1:
              order: 1
              instruction: Spread the avocado onto the cracker.
            step2:
              order: 1
              instruction: Spread the avocado onto the cracker.
            step3:
              order: 1
              instruction: Spread the avocado onto the cracker.
      items:
        type: object
        properties:
          step1:
            $ref: '#/components/schemas/Step'
          step2:
            $ref: '#/components/schemas/Step'
          step3:
            $ref: '#/components/schemas/Step'
  parameters:
    recipeId:
      name: recipeId
      in: path
      required: true
      schema:
        type: integer
        minimum: 0
        format: int64
        example: 0
      description: Unique recipe identifier.
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Bad Request
          examples:
            Bad Request:
              value:
                message: Bad Request
    '404':
      description: Recipe not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Recipe not found
          examples:
            Recipe not found:
              value:
                message: Recipe not found
  examples: {}
